export const scaleActionType = {
    SET_TILE : "SET_TILE",
    SET_DEFAULT_TILE:"SET_DEFAULT_TILE",
    SET_SUIT_TILE : "SET_SUIT_TILE",
    SET_COLLAR_TILE : "SET_COLLAR_TILE",
    RENDERING : "RENDERING",
    FETCH_INPUTS:"FETCH_INPUTS"
}