export const uploadActionType = {
    FETCH_DIRS: "FETCH_DIRS",
    SET_NAME: "SET_NAME",
    SET_CONTENT: "SET_CONTENT",
    SET_PRICE: "SET_PRICE",
    SET_DIFFUSE: "SET_DIFFUSE",
    SET_ALPHA: "SET_ALPHA",
    SET_ROUGHNESS: "SET_ROUGHNESS",
    SET_METAL: "SET_METAL",
    SET_ICON: "SET_ICON",
    SET_NORMAL: "SET_NORMAL",
    SET_DONE:"SET_DONE",
    CLEAR_DATA:"CLEAR_DATA",
    SET_COLOR:"SET_COLOR",
    SET_COLOR_PREVIEW:"SET_COLOR_PREVIEW",

}