export const HomeActionType = {
    FETCH_MENU:"FETCH_MENU",
    FETCH_DEFAULT:"FETCH_DEFAULT",
    FETCH_INNER_LIST:"FETCH_INNER_LIST",
    TOGGLE_INNER_LIST:"TOGGLE_INNER_LIST",
    FETCH_FABRIC:"FETCH_FABRIC",
    FETCH_LINING:"FETCH_LINING",
    FETCH_BUTTON:"FETCH_BUTTON",
    FETCH_MATERIAL:"FETCH_MATERIAL",
    MATERIAL_SELECTED:"MATERIAL_SELECTED",
    CHANGE_SHOT:"CHANGE_SHOT"
}